### ISSUE TITLE
Failed to load the hover-tooltips-hdevtools package

### ISSUE THREAD

**Issue by tnrn9b** [ranjitjhala/hover-tooltips-hdevtools#2]
[Enter steps to reproduce below:]
1. Just happened with an update to the following packages:
                 haskell-ghc-mod, v0.9.10
                 hover-tooltips-hdevtools, v0.7.0
                 ide-haskell, v0.7.2
               [ update failed initially: language-haskell, v1.4.4 ]

Folllowing the error, I updated to langauge-haskell, v1.4.6.
1. ...

**Atom Version**: 1.0.15
**System**: Microsoft Windows 10 Pro
**Thrown From**: [hover-tooltips-hdevtools](https://github.com/ranjitjhala/hover-tooltips-hdevtools) package, v0.7.0
### Stack Trace

Failed to load the hover-tooltips-hdevtools package

```
At Cannot find module './hover-tooltips'

Error: Cannot find module './hover-tooltips'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\T\AppData\Local\atom\app-1.0.15\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\T\.atom\packages\hover-tooltips-hdevtools\lib\hover-tooltips-hdevtools.js:7:24)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\T\AppData\Local\atom\app-1.0.15\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-haskell, v0.5.1
haskell-ghc-mod, v0.9.10
haskell-grammar, v0.4.0
haskell-pointfree, v0.1.2
hover-tooltips-hdevtools, v0.7.0
ide-haskell, v0.7.2
language-coq, v0.1.0
language-haskell, v1.4.4

# Dev
No dev packages
```

**Comment by tnrn9b** [comment]
Ok, this isn't an issue. It was the order of the updates that caused the error. Once the error was thrown, the update must have aborted. Or, some such non-sense like that.
