### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by notcome** [ranjitjhala/hover-tooltips-hdevtools#3]
[Enter steps to reproduce below:]
1. Open any file, .hs and others
2. Bang!

Seems to be a upstream API broken? I can find some similar issue, like [this](https://github.com/OmniSharp/omnisharp-atom/issues/533) and [this](https://github.com/TypeStrong/atom-typescript/issues/647).

A useful comment from the later:

> Submitted a pull request that fixes this. Apparently getScrollTop() and getScrollLeft() was moved to the editor.

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11
**Thrown From**: [hover-tooltips-hdevtools](https://github.com/ranjitjhala/hover-tooltips-hdevtools) package, v0.8.0
### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At /Users/Liu.MS/.atom/packages/hover-tooltips-hdevtools/node_modules/hover-tooltips/lib/hover-tooltips.js:53

TypeError: editor.displayBuffer.getScrollTop is not a function
    at showExpressionType (/Users/Liu.MS/.atom/packages/hover-tooltips-hdevtools/node_modules/hover-tooltips/lib/hover-tooltips.js:53:49)
    at /Users/Liu.MS/.atom/packages/hover-tooltips-hdevtools/node_modules/hover-tooltips/lib/hover-tooltips.js:40:63
```
### Commands

```
```
### Config

``` json
{
  "core": {},
  "hover-tooltips-hdevtools": {}
}
```
### Installed Packages

``` coffee
# User
hex, v0.6.2
hover-tooltips-hdevtools, v0.8.0
language-haskell, v1.4.12
language-latex, v0.6.1
linter, v1.10.0
linter-hdevtools, v1.6.0

# Dev
No dev packages
```

**Comment by notcome** [comment]
Should be the problem of hover-tooltips.

**Comment by notcome** [comment]
So, in [hover-tooltips.js](https://github.com/ranjitjhala/hover-tooltips/blob/8db8144da1b2ffc43918c80afdf8f114682e50a2/lib/hover-tooltips.js#L53-L54)

Changing it to the following solves the issue:

``` javascript
//pixelPt.top += editor.displayBuffer.getScrollTop();
pixelPt.top += editor.getScrollTop();
//pixelPt.left += editor.displayBuffer.getScrollLeft();
pixelPt.left += editor.getScrollLeft();
```

I don't have a TypeScript development environment at hand and am a bit unfamiliar with it, so unfortunately I couldn't send a pull request.

**Comment by ranjitjhala** [comment]
Thanks for pointing out, I _believe_ this is fixed by https://github.com/ranjitjhala/hover-tooltips/pull/3 ?

Can you just upgrade the package  -- `apm install hover-tooltips-hdevtools`  -- and let me know if this is fixed? Thanks!

**Comment by ericmdantas** [comment]
@ranjitjhala that worked for me, thanks!
